# .github/workflows/dependabot-action.yml
name: Dependabot

on:
  push:
  
  schedule:
    - cron: "*/5 * * * *"  # Run every day, adjust the schedule as needed

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Dependabot
        uses: dependabot/dependabot-core@main  # Use 'main' branch reference
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: "npm update"
