# .github/workflows/dependabot-action.yml
name: Dependabot

on:
  push:
    branches:
      - main  # Adjust this based on your main branch name
  schedule:
    - cron: "*/2 * * * *"  # Run every day, adjust the schedule as needed

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Dependabot
        run: npx dependabot 
